### ISSUE TITLE
Retrieve "sleep" data from GoogleFit

### ISSUE THREAD

**Issue by proffalken** [connectordb/connectordb-android#3]
This works really well on my android phone for steps/browsing habits etc, so thanks! :)

I use http://sleep.urbandroid.org/ to send my sleep data into GoogleFit, is there any way that I can have connectordb-android pull the sleep metrics out of GoogleFit and add it as a datastream in the same way that it does for Steps?

I've had a quick look at the source code, however as the only mention of the loggers described in the README are in the `old` directory, I'm guessing a pretty comprehensive rewrite is underway?

**Comment by dkumor** [comment]
Yes - the entire app is undergoing an overhaul. The new data-collection code should take shape in the next 2 weeks. 

I will make sure to see whether further google fit data could be auto-gathered when upgrading google fit code.

**Comment by dkumor** [comment]
Logging from Sleep As Android is in testing channel.

**Comment by proffalken** [comment]
Awesome, thanks!

How do I get access to that testing channel? Is there somewhere I can subscribe to beta updates? 

I'm doing a talk next week on QS and ConnectorDB is going to form the heart of it! :)

**Comment by dkumor** [comment]
https://play.google.com/apps/testing/com.connectordb_android

Testing channel available above!

PS: If doing a talk, you might want to update the frontend to the [newest version](https://keybase.pub/dkumor/connectordb/) too (git.1117), since it now offers a (very alpha) analysis tab, enabling you to correlate streams. You might need to clear your browser's service worker to see the new version.

**Comment by proffalken** [comment]
Brilliant, thanks, I'll update the app now and the Frontend later on tonight or tomorrow :)

**Comment by proffalken** [comment]
OK, app updated, re-compiled the server from latest git as I'm running on arm64 (https://www.pine64.org/) but the version is `0.3.0git1116` not `0.3.0git1117` as in the download.

Happy to log this as a different issue if you want?

UI is definitely more snappy in this release :)

**Comment by dkumor** [comment]
did you do a git pull?  If you now have 2 new options (downlinks & analysis) in addition to Insert & Devices, and `connectordb --version` says

```
git: 4293b0c14e9570112a33b2697ede3ed3b947e141
```

then you are running the most recent release.

**Comment by proffalken** [comment]
OK, I've got the latter hash now, so at least I know it's the right commit, I still don't have the UI changes so I've done a "make clean" and now I'm re-running the build process, I'll get back to you with the results.

**Comment by dkumor** [comment]
I did not update the service worker. To get the UI changes, you will need to go to chrome developer settings -> Application -> Clear Site Data, which will unregister the old service worker.

I will make the service worker auto-update on commit in the future.

**Comment by proffalken** [comment]
OK, all working again, had to copy over the `bundle*.js` files from the downloaded release however as `make`, `make deps` and `npm run build` didn't create them.

I'll log a new ticket for that against the server
